server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false
plugins:
     lavasrc:
        providers:
          - "dzisrc:%ISRC%"
          - "dzsearch:%QUERY%"
          - "ytsearch:\"%ISRC%\""
          - "ytsearch:%QUERY%"
        sources:
          spotify: true
          applemusic: true
          deezer: true
          yandexmusic: true
          flowerytts: false
          youtube: true
        spotify:
          clientId: "your client id"
          clientSecret: "your client secret"
          countryCode: "IN"
          playlistLoadLimit: 6
          albumLoadLimit: 6
        # applemusic:
        #   countryCode: "US" # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
        #   mediaAPIToken: "your apple music api token" # apple music api token
        #   # or specify an apple music key
        #   keyID: "your key id"
        #   teamID: "your team id"
        #   musicKitKey: |
        #     -----BEGIN PRIVATE KEY-----
        #     your key
        #     -----END PRIVATE KEY-----      
        #   playlistLoadLimit: 6 # The number of pages at 300 tracks each
        #   albumLoadLimit: 6 # The number of pages at 300 tracks each
        deezer:
          masterDecryptionKey: "your master decryption key" # the master key used for decrypting the deezer tracks. (yes this is not here you need to get it from somewhere else)
        # yandexmusic:
        #   accessToken: "your access token" # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music
        # flowerytts:
        #   voice: "default voice" # (case-sensitive) get default voice from here https://api.flowery.pw/v1/tts/voices
        #   translate: false # whether to translate the text to the native language of voice
        #   silence: 0 # the silence parameter is in milliseconds. Range is 0 to 10000. The default is 0.
        #   speed: 1.0 # the speed parameter is a float between 0.5 and 10. The default is 1.0. (0.5 is half speed, 2.0 is double speed, etc.)
        #   audioFormat: "mp3" # supported formats are: mp3, ogg_opus, ogg_vorbis, aac, wav, and flac. Default format is mp3

    dunctebot:
        ttsLanguage: "en-AU"
        sources:
            getyarn: true
            clypit: true
            tts: true
            pornhub: true
            reddit: true
            ocremix: true
            tiktok: true
            mixcloud: true
            soundgasm: true
lavalink:
  plugins:
    - dependency: "com.dunctebot:skybot-lavalink-plugin:1.5.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "aqu@az_drex!y"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
    #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
    #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
    #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
    #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
    #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
    #email: "" # Email of Google account
    #password: "" # Password of Google account
    #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
    #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
    #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
    #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
    #proxyPassword: "" # Password for basic authentication

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
